apiVersion: v1
kind: Service
metadata:
  name: super-fun-website
spec:
  selector:
    app: super-fun-website
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8090
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-fun-website
spec:
  selector:
    matchLabels:
      app: super-fun-website
  replicas: 4
  template:
    metadata:
      labels:
        app: super-fun-website
    spec:
      containers:
      - name: super-fun-website
        image: super-fun-website:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8090
        env:
          # Define the environment variable
          - name: CFMAP_KEY 
            valueFrom:
              configMapKeyRef:
                name: super-fun-map
                key: super-fun-key

---
apiVersion: v1
kind: Pod

metadata:
  labels:
    test: liveness
  name: super-fun-website-health

spec:
  containers:
  - name: super-fun-website-health
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthz; sleep 40; rm -f /tmp/healthz; sleep 700

    livenessProbe:
      httpGet:
        path: /
        port: 8090
    readinessProbe:
      httpGet:
        path: /
        port: 8090
